---
title: "Partial Search and Bias Metrics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Partial Search and Bias Metrics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r}
library(AutomaticMGCFA)
```

## Partial Search with Multi-Rule Decisions

```{r}
out <- mgcfa_auto(
  model_type = "custom",
  model = "F =~ x1 + x2 + x3 + x4",
  input = mgcfa_prepare_input(data = dat, group = "grp"),
  partial_failure_rules = list(
    list(criterion = "chisq_pvalue", threshold = 0.05),
    list(criterion = "delta_cfi", threshold = 0.01),
    list(criterion = "measure_change", measure = "aic", direction = "decrease", threshold = 0)
  ),
  partial_failure_rule_policy = "at_least",
  partial_failure_rule_min = 2L,
  partial_auto_search = "always",
  partial_search_parallel = TRUE,
  partial_search_n_cores = 4
)
```

## Bias Effect Sizes

```{r}
bias <- mgcfa_bias_effects(
  out,
  include_items = TRUE,
  ci = TRUE,
  n_boot = 200,
  conf_level = 0.95
)

head(bias$effect_size_metrics)
head(bias$effect_size_metrics_ci)
head(bias$effect_size_recovery)
```
